server:
  port: 4043
spring:
  application:
    name: test-cloud-clienta
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: test-cloud
        namespace: a91cf009-9642-4c46-bc20-202aebc94f4d
  security:
    oauth2:
      # 资源服务器配置
      resourceserver:
        jwt:
          # Jwt中claims的iss属性，也就是jwt的签发地址，即认证服务器的根路径
          # 资源服务器会进一步的配置，通过该地址获取公钥以解析jwt
          issuer-uri: http://auth.flow.com
